# Generated by Django 5.1.4 on 2024-12-16 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Event Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='event_images/', verbose_name='Event Image')),
                ('max_attendees', models.PositiveIntegerField(verbose_name='Max Attendees')),
                ('time_date', models.DateTimeField(verbose_name='Event Date & Time')),
                ('place', models.CharField(max_length=255, verbose_name='Event Place')),
                ('guests', models.TextField(blank=True, null=True, verbose_name='Guest Names (Comma-separated)')),
                ('actual_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Actual Ticket Amount')),
                ('offer_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Offer Ticket Amount')),
                ('enquiry_number', models.CharField(max_length=15, verbose_name='Enquiry Number')),
            ],
            options={
                'verbose_name': 'event',
                'verbose_name_plural': 'events',
                'db_table': 'event',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slider_image')),
                ('title', models.CharField(max_length=255)),
                ('short_description', models.TextField()),
            ],
            options={
                'verbose_name': 'slider',
                'verbose_name_plural': 'sliders',
                'db_table': 'slider',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'customer',
                'verbose_name_plural': 'customers',
                'db_table': 'customer_customer',
                'ordering': ['-id'],
            },
        ),
    ]
