# Generated by Django 5.1.4 on 2024-12-17 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='enquiry_number',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='guests',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(default=1, upload_to='event_images'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='max_attendees',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='place',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='time_date',
            field=models.DateTimeField(),
        ),
    ]
