# Generated by Django 5.1.4 on 2024-12-19 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_remove_event_admin_fee_remove_event_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='admin_fee',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=6, verbose_name='Admin Fee'),
        ),
    ]
