# Generated by Django 5.1.4 on 2024-12-19 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_event_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='tax_charge',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
