# Generated by Django 5.1.4 on 2024-12-19 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_event_tax_charge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='tax_charge',
        ),
        migrations.AddField(
            model_name='event',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.customer'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CartBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_amount', models.FloatField()),
                ('offer_amount', models.FloatField()),
                ('totel_amount', models.FloatField()),
                ('tax_charge', models.FloatField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.customer')),
            ],
            options={
                'verbose_name': 'cartbill',
                'verbose_name_plural': 'cartbills',
                'db_table': 'cartbill',
                'ordering': ['-id'],
            },
        ),
    ]
