# Generated by Django 5.0.1 on 2024-12-19 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_alter_cartbill_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='customer',
        ),
    ]
