# Generated by Django 5.1.4 on 2024-12-19 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_remove_event_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='actual_amount',
        ),
        migrations.RemoveField(
            model_name='event',
            name='offer_amount',
        ),
        migrations.AddField(
            model_name='event',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='enquiry_number',
            field=models.IntegerField(),
        ),
    ]
