# Generated by Django 5.1.4 on 2024-12-19 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_remove_event_actual_amount_remove_event_offer_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='actual_amount',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='offer_amount',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
