# Generated by Django 5.1.4 on 2024-12-19 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_event_actual_amount_event_offer_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='actual_amount',
        ),
        migrations.RemoveField(
            model_name='event',
            name='offer_amount',
        ),
    ]
