# Generated by Django 5.1.4 on 2024-12-19 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_remove_event_price_event_actual_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='actual_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Actual Ticket Amount'),
        ),
        migrations.AlterField(
            model_name='event',
            name='enquiry_number',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='offer_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Offer Ticket Amount'),
        ),
    ]
