# Generated by Django 5.1.4 on 2024-12-20 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_alter_event_actual_amount_alter_event_enquiry_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_actived',
            field=models.BooleanField(default=True),
        ),
    ]
